### ISSUE TITLE
PlayState Crash

### ISSUE THREAD

**Issue by phrGithubGamerBR** [DEMOLITIONDON96/FE-Feather-Custom#13]
openfl/media/Sound.hx (line 407)
globals/Paths.hx (line 221)
states/PlayState.hx (line 1802)
states/PlayState.hx (line 424)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 426)
openfl/display/DisplayObject.hx (line 1398)

Uncaught Error: Error loading sound from file: assets/songs/test/VoicesBF.ogg - Please report this error to the
GitHub page https://github.com/DEMOLITIONDON96/Spectra-Engine

I didn't change anything

**Comment by FuckingAltLol** [comment]
yeah, this engine is likely gonna get a rewrite in the future, most of the code I made here is just shit and I'm not a fan with how it turned out, so look forward to that

**Comment by phrGithubGamerBR** [comment]
> yeah, this engine is likely gonna get a rewrite in the future, most of the code I made here is just shit and I'm not a fan with how it turned out, so look forward to that

oh ok
