### ISSUE TITLE
[HELP] Error Compiling

### ISSUE THREAD

**Issue by oofienoob** [DEMOLITIONDON96/FE-Feather-Custom#7]
Hello, this isn't really urgent but whenever I compile, 
I get this error; I have the git version of SScript, 
![image_2023-09-07_213355484](https://github.com/DEMOLITIONDON96/FE-Feather-Custom/assets/143152154/63c699a1-c7c7-48b9-af77-8eb441b875fc)

Which libraries do I have to Install for compilation?

**Comment by oofienoob** [comment]
The reason why I made this is because I'm planning on making a mod using the original Forever Engine feather.
So please, if you can help, it'll be gladly appreciated.

**Comment by DEMOLITIONDON96** [comment]
> The reason why I made this is because I'm planning on making a mod using the original Forever Engine feather. So please, if you can help, it'll be gladly appreciated.

hi, the reason why SScript doesn't work for you is due to the fact I haven't updated the bat files with the NEW replacement due to the old one getting updated and breaking everything, so here's the SScript you can use that I made on an alt account :)

https://github.com/FuckingAltLol/SScript

**Comment by oofienoob** [comment]
Alright, thank you very much :D
